// app/api/orders/route.js
import { NextResponse } from "next/server";
import { supabase } from "@/lib/supabase";

export async function POST(request) {
  try {
    const {
      orderId,
      customer,
      items,
      total,
      wavePaymentId,
      notes
    } = await request.json();

    // build a single shipping_address string
    const shipping_address = customer.suite
      ? `${customer.address}, ${customer.suite}`
      : customer.address;

    // insert into orders
    const { data, error } = await supabase
      .from("orders")
      .insert([
        {
          id: orderId,  // id will be generated by default
          customer_name:  `${customer.firstName} ${customer.lastName}`,
          customer_email: customer.email,
          customer_phone: customer.phone,
          shipping_address,
          city:           customer.city,
          items,          // JSONB column: cart items array
          total,          // integer
          wave_payment_id: wavePaymentId,
          notes:          notes || null
        },
      ])
      .select()
      .single();

    if (error) {
      console.error("Insert order error:", error);
      throw error;
    }

    return NextResponse.json({ order: data });
  } catch (e) {
    console.error("API/orders error:", e);
    return NextResponse.json(
      { error: e.message || "Unexpected error" },
      { status: 500 }
    );
  }
}

export async function PUT(request) {
  const { orderId, items, total, wavePaymentId, notes, succeeded } = await request.json()

  const { data, error } = await supabase
    .from('orders')
    .update({
      items,                     // your JSONB cart
      total,
      wave_payment_id: wavePaymentId,
      notes: notes || null,
      payment_status: succeeded  // 'succeeded' or pass 'cancelled'
    })
    .eq('id', orderId)
    .select()
    .single()

  if (error) {
    console.error('Finalize order error:', error)
    return NextResponse.json({ error: error.message }, { status: 500 })
  }

  return NextResponse.json({ order: data })
}
